pipeline {
    agent any
    tools { 
        maven 'Maven 3.5.2' 
        jdk 'jdk-13.0.1+9' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                echo "PATH = ${PATH}"
                java -version
                '''
            }
        }

        stage ('Build') {
            steps {
                echo 'This is a minimal pipeline.'
            }
        }
    }
}