pipeline {
    agent any
    tools { 
        maven 'Maven 3.5.2' 
        jdk 'jdk-13.0.1+9' 
    }
    stages {
        stage ('Initialize') {
            steps {
                #sh 'java -version'
                sh 'echo "PATH = ${PATH}"'
            }
        }

        stage ('Build') {
            steps {
                echo 'This is a minimal pipeline.'
            }
        }
    }
}